services:
  postgres:
    image: postgres:16-alpine
    container_name: workout-tracker-db
    environment:
      POSTGRES_DB: ${DB_NAME:-workout_tracker}
      POSTGRES_USER: ${DB_USER:-workout_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-workout_pass}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workout-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-workout_user} -d ${DB_NAME:-workout_tracker}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-tracker-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-workout_tracker}
      DB_USER: ${DB_USER:-workout_user}
      DB_PASSWORD: ${DB_PASSWORD:-workout_pass}
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123!@#WorkoutTrackerSecretKey2024}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - workout-network
    volumes:
      - ./logs:/app/logs

networks:
  workout-network:
    driver: bridge

volumes:
  postgres_data: